name: Qodana (Calidad de Código)

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Crucial: Qodana necesita ver el historial de Git para analizar los cambios

      - name: Ejecutar análisis de Qodana
        uses: jetbrains/qodana-action@v2024.1